### ISSUE TITLE
Implement real FileID's

### ISSUE THREAD

**Issue by Trojaner** [DiscordFS/DiscordFS#22]
Currently placeholders use fake FileID's with new random GUID's.
Implement real FileID's via index.db.

- What is the FileID used for?
- Does it persist if the file moves or gets deleted?
- Used in: CfConvertToPlaceholder

**Comment by jaty613** [comment]
StorageProviderSyncRootManager.Register(syncRootInfo);  // error


![image](https://user-images.githubusercontent.com/3693273/231839987-53f0cd53-5ccd-4fa0-a904-2973cb9beff4.png)
![image](https://user-images.githubusercontent.com/3693273/231840013-2c5b2d76-f6a0-4586-aa2b-2122a9566639.png)
![image](https://user-images.githubusercontent.com/3693273/231840043-dbe55014-1385-4045-8b8d-f8429de126ee.png)

**Comment by jaty613** [comment]
System.Runtime.InteropServices.COMException (0x8000000B): The operation attempted to access data outside the valid range (0x8000000B)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.Storage.Provider.IStorageProviderSyncRootManagerStaticsMethods.Register(IObjectReference _obj, StorageProviderSyncRootInfo syncRootInformation)
   at Windows.Storage.Provider.StorageProviderSyncRootManager.Register(StorageProviderSyncRootInfo syncRootInformation)
   at DiscordFS.Storage.BaseStorageProvider`1.RegisterAsync(TOptions options)
   at DiscordFS.MainPage.OnPageLoaded(Object sender, EventArgs e)
